
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HospitalManagament
{

using System;
    using System.Collections.Generic;
    
public partial class Event
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Event()
    {

        this.allDay = false;

        this.Status = true;

        this.URL = "javascript:void(0)";

    }


    public long Id { get; set; }

    public Nullable<System.DateTime> Start { get; set; }

    public Nullable<System.DateTime> End { get; set; }

    public Nullable<bool> allDay { get; set; }

    public long UserId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Nullable<bool> Status { get; set; }

    public string StartDateStr { get; set; }

    public Nullable<System.TimeSpan> StartTime { get; set; }

    public string EndDateStr { get; set; }

    public Nullable<System.TimeSpan> EndTime { get; set; }

    public string URL { get; set; }



    public virtual User User { get; set; }

}

}
